name: Rebuild Website after Changes

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build_website/requirements.txt

    - name: Add .gitkeep files to empty directories
      run: |
        python build_website/add_gitkeep.py

    - name: Run main.py
      run: |
        python build_website/main.py

    - name: Commit and push changes if there are any
      id: commit
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
          echo "::set-output name=changes::false"
        else
          git commit -m 'Update repository with new build (GitHub Action)'
          git push origin main
          echo "::set-output name=changes::true"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
